server:
  port: 8108

spring:
  application:
    name: inube-authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5437/aba
    username : aba
    password: aba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: e4b7f9d2a13c4efb92d7c31ae8f04c9bd3e27fa649c8d1e0b57a23cf8b9e41ac

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8106/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15

    preferIpAddress: true
