
spring:
  application:
    name: inube-gateway-service
  security:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: inube-auth-auth
          uri: lb://INUBE-AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/inube/auth/**
        - id: inube-auth-user
          uri: lb://INUBE-AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/inube/user/**
        - id: inube-service
          uri: lb://INUBE-SERVICE
          predicates:
            - Path=/api/inube/service/**
          filters:
            - AuthenticationFilter
          
   

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8106/eureka/
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true

jwt:
  secret: e4b7f9d2a13c4efb92d7c31ae8f04c9bd3e27fa649c8d1e0b57a23cf8b9e41ac

server:

  port: 8107
