spring:
   application:
    name: inube-gateway-service
security:
  enable: false
cloud:
  gateway:
    discovery:
      locator:
         enable: false
         lower-case-service-id: true
      routes:
        - id: inube-auth-auth
          uri: lb://INUBE-AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/inube/auth/**
        - id: inube-service
          uri: lb://INUBE-AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/inube/service/**
        - id: inube-service
          uri: lb://INUBE-SERVICE 
          predicates:
            - path=/api/inube/service/**
          filters:
            - AuthenticationFilter



eureka:
  client:
    service:
      defaultZone: http://localhost:8106/eureka/
    regsiterWithEureka: true
    fetchRegistry: true
    healthcheck:
      enable: true
  instance:
     leaseRenawalIntervalInSeconds: 5
     leaseExpirationDurationInSeconds: 15
     preferIpAddress: true

jwt:
  secret: e4b7f9d2a13c4efb92d7c31ae8f04c9db3e27fa649c8d1e0b57a23cf8b9e41ac

server:

  port: 8107
